
server:
  port: 8080

spring:
  application:
    name: api-gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8769/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    status-page-url: http://api-gateway-service/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 10000

zuul:
  routes:
    orders:
      path: /orders/**
      serviceId: orders-service
      strip-prefix: false
    warehouse:
      path: /warehouse/**
      serviceId: items-service
      strip-prefix: false
    payments:
      path: /payments/**
      serviceId: payments-service
      strip-prefix: false
    orderpaid:
      path: /orderpaid/**
      serviceId: api-gateway-service
      strip-prefix: false