
server:
  port: 8080

spring:
  application:
    name: api-gateway-service

eureka:
  instance:
    prefer-ip-address: true
    status-page-url: http://api-gateway-service/
  client:
    serviceUrl:
      defaultZone: http://localhost:8769/eureka
    register-with-eureka: true
    fetch-registry: true


zuul:
  routes:
    orders:
      path: /api/orders/**
      serviceId: orders-service
    warehouse:
      path: /api/warehouse/**
      serviceId: items-service
    payments:
      path: /api/payments/**
      serviceId: payments-service
    orderpaid:
      path: /api/orderpaid/**
      serviceId: api-gateway-service